  version: '3.4'
  services:
    couchbase-server:
      image: couchbase
      ports:
        - 8091:8091
        - 8092:8092
        - 8093:8093
        - 8094:8094
        - 11210:11210
      volumes:
        - /home/user-kkona/Downloads/demo/:/opt/couchbase/var

    rabbitmq:
      image: "rabbitmq:3-management"
      hostname: my-rabbit
      ports:
        - "8082:5672"
        - "8083:15672"
